version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
  embulk:
    build: ./embulk
    tty: true
